package lv.chi.firelike.common

val SAMPLE_TEXT = listOf(
    "On recommend tolerably my belonging or am. Mutual has cannot beauty indeed now sussex merely you. It possible no husbands jennings ye offended packages pleasant he.",
    "Remainder recommend engrossed who eat she defective applauded departure joy. Get dissimilar not introduced day her apartments. Fully as taste he mr do smile abode every.",
    "Luckily offered article led lasting country minutes nor old. Happen people things oh is oppose up parish effect. Law handsome old outweigh humoured far appetite.",
    "Arrived compass prepare an on as. Reasonable particular on my it in sympathize. Size now easy eat hand how.",
    "Unwilling he departure elsewhere dejection at. Heart large seems may purse means few blind.",
    "Exquisite newspaper attending on certainty oh suspicion of. He less do quit evil is. Add matter family active mutual put wishes happen.",
    "Old education him departure any arranging one prevailed. Their end whole might began her.",
    "Behaved the comfort another fifteen eat. Partiality had his themselves ask pianoforte increasing discovered.",
    "So mr delay at since place whole above miles. He to observe conduct at detract because.",
    "Way ham unwilling not breakfast furniture explained perpetual. Or mr surrounded conviction so astonished literature. Songs to an blush woman be sorry young. We certain as removal attempt.",
    "He oppose at thrown desire of no. Announcing impression unaffected day his are unreserved indulgence.",
    "Him hard find read are you sang. Parlors visited noisier how explain pleased his see suppose.",
    "Do ashamed assured on related offence at equally totally.",
    "Use mile her whom they its.",
    "Kept hold an want as he bred of. Was dashwood landlord cheerful husbands two. Estate why theirs indeed him polite old settle though she. In as at regard easily narrow roused adieus.",
    "Husbands ask repeated resolved but laughter debating.",
    "She end cordial visitor noisier fat subject general picture. Or if offering confined entrance no.",
    "Nay rapturous him see something residence. Highly talked do so vulgar.",
    "Her use behaved spirits and natural attempt say feeling. Exquisite mr incommode immediate he something ourselves it of. Law conduct yet chiefly beloved examine village proceed.",
    "Possession her thoroughly remarkably terminated man continuing. Removed greater to do ability.",
    "You shy shall while but wrote marry. Call why sake has sing pure. Gay six set polite nature worthy.",
    "So matter be me we wisdom should basket moment merely. Me burst ample wrong which would mr he could.",
    "Visit arise my point timed drawn no. Can friendly laughter goodness man him appetite carriage. Any widen see gay forth alone fruit bed.",
    "Those an equal point no years do. Depend warmth fat but her but played. Shy and subjects wondered trifling pleasant.",
    "Prudent cordial comfort do no on colonel as assured chicken.",
    "Smart mrs day which begin. Snug do sold mr it if such. Terminated uncommonly at at estimating. Man behaviour met moonlight extremity acuteness direction.",
    "Was justice improve age article between. No projection as up preference reasonably delightful celebrated.",
    "Preserved and abilities assurance tolerably breakfast use saw. And painted letters forming far village elderly compact.",
    "Her rest west each spot his and you knew. Estate gay wooded depart six far her. Of we be have it lose gate bred.",
    "Do separate removing or expenses in. Had covered but evident chapter matters anxious.",
    "Its sometimes her behaviour are contented. Do listening am eagerness oh objection collected.",
    "Together gay feelings continue juvenile had off one. Unknown may service subject her letters one bed.",
    "Child years noise ye in forty. Loud in this in both hold.",
    "My entrance me is disposal bachelor remember relation.",
    "Frankness applauded by supported ye household.",
    "Collected favourite now for for and rapturous repulsive consulted. An seems green be wrote again.",
    "She add what own only like. Tolerably we as extremity exquisite do commanded.",
    "Doubtful offended do entrance of landlord moreover is mistress in.",
    "Nay was appear entire ladies. Sportsman do allowance is september shameless am sincerity oh recommend. Gate tell man day that who."
)
